# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dlp_pb2 as dlp__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dlp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DLPInspectorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inspect = channel.unary_unary(
                '/dlp.DLPInspector/Inspect',
                request_serializer=dlp__pb2.InspectRequest.SerializeToString,
                response_deserializer=dlp__pb2.Verdict.FromString,
                _registered_method=True)


class DLPInspectorServicer:
    """Missing associated documentation comment in .proto file."""

    def Inspect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DLPInspectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=dlp__pb2.InspectRequest.FromString,
                    response_serializer=dlp__pb2.Verdict.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dlp.DLPInspector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dlp.DLPInspector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DLPInspector:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dlp.DLPInspector/Inspect',
            dlp__pb2.InspectRequest.SerializeToString,
            dlp__pb2.Verdict.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
